// We will use this data if the fetch fails
export const repos = [
	{
		id: 415342906,
		node_id: "R_kgDOGMGhOg",
		name: "svelte-outclick",
		full_name: "babakfp/svelte-outclick",
		private: false,
		owner: {
			login: "babakfp",
			id: 44144724,
			node_id: "MDQ6VXNlcjQ0MTQ0NzI0",
			avatar_url: "https://avatars.githubusercontent.com/u/44144724?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/babakfp",
			html_url: "https://github.com/babakfp",
			followers_url: "https://api.github.com/users/babakfp/followers",
			following_url: "https://api.github.com/users/babakfp/following{/other_user}",
			gists_url: "https://api.github.com/users/babakfp/gists{/gist_id}",
			starred_url: "https://api.github.com/users/babakfp/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/babakfp/subscriptions",
			organizations_url: "https://api.github.com/users/babakfp/orgs",
			repos_url: "https://api.github.com/users/babakfp/repos",
			events_url: "https://api.github.com/users/babakfp/events{/privacy}",
			received_events_url: "https://api.github.com/users/babakfp/received_events",
			type: "User",
			site_admin: false,
		},
		html_url: "https://github.com/babakfp/svelte-outclick",
		description:
			"A Svelte component that allows you to listen to the clicks that happen outside of an element.",
		fork: false,
		url: "https://api.github.com/repos/babakfp/svelte-outclick",
		forks_url: "https://api.github.com/repos/babakfp/svelte-outclick/forks",
		keys_url: "https://api.github.com/repos/babakfp/svelte-outclick/keys{/key_id}",
		collaborators_url:
			"https://api.github.com/repos/babakfp/svelte-outclick/collaborators{/collaborator}",
		teams_url: "https://api.github.com/repos/babakfp/svelte-outclick/teams",
		hooks_url: "https://api.github.com/repos/babakfp/svelte-outclick/hooks",
		issue_events_url: "https://api.github.com/repos/babakfp/svelte-outclick/issues/events{/number}",
		events_url: "https://api.github.com/repos/babakfp/svelte-outclick/events",
		assignees_url: "https://api.github.com/repos/babakfp/svelte-outclick/assignees{/user}",
		branches_url: "https://api.github.com/repos/babakfp/svelte-outclick/branches{/branch}",
		tags_url: "https://api.github.com/repos/babakfp/svelte-outclick/tags",
		blobs_url: "https://api.github.com/repos/babakfp/svelte-outclick/git/blobs{/sha}",
		git_tags_url: "https://api.github.com/repos/babakfp/svelte-outclick/git/tags{/sha}",
		git_refs_url: "https://api.github.com/repos/babakfp/svelte-outclick/git/refs{/sha}",
		trees_url: "https://api.github.com/repos/babakfp/svelte-outclick/git/trees{/sha}",
		statuses_url: "https://api.github.com/repos/babakfp/svelte-outclick/statuses/{sha}",
		languages_url: "https://api.github.com/repos/babakfp/svelte-outclick/languages",
		stargazers_url: "https://api.github.com/repos/babakfp/svelte-outclick/stargazers",
		contributors_url: "https://api.github.com/repos/babakfp/svelte-outclick/contributors",
		subscribers_url: "https://api.github.com/repos/babakfp/svelte-outclick/subscribers",
		subscription_url: "https://api.github.com/repos/babakfp/svelte-outclick/subscription",
		commits_url: "https://api.github.com/repos/babakfp/svelte-outclick/commits{/sha}",
		git_commits_url: "https://api.github.com/repos/babakfp/svelte-outclick/git/commits{/sha}",
		comments_url: "https://api.github.com/repos/babakfp/svelte-outclick/comments{/number}",
		issue_comment_url:
			"https://api.github.com/repos/babakfp/svelte-outclick/issues/comments{/number}",
		contents_url: "https://api.github.com/repos/babakfp/svelte-outclick/contents/{+path}",
		compare_url: "https://api.github.com/repos/babakfp/svelte-outclick/compare/{base}...{head}",
		merges_url: "https://api.github.com/repos/babakfp/svelte-outclick/merges",
		archive_url: "https://api.github.com/repos/babakfp/svelte-outclick/{archive_format}{/ref}",
		downloads_url: "https://api.github.com/repos/babakfp/svelte-outclick/downloads",
		issues_url: "https://api.github.com/repos/babakfp/svelte-outclick/issues{/number}",
		pulls_url: "https://api.github.com/repos/babakfp/svelte-outclick/pulls{/number}",
		milestones_url: "https://api.github.com/repos/babakfp/svelte-outclick/milestones{/number}",
		notifications_url:
			"https://api.github.com/repos/babakfp/svelte-outclick/notifications{?since,all,participating}",
		labels_url: "https://api.github.com/repos/babakfp/svelte-outclick/labels{/name}",
		releases_url: "https://api.github.com/repos/babakfp/svelte-outclick/releases{/id}",
		deployments_url: "https://api.github.com/repos/babakfp/svelte-outclick/deployments",
		created_at: "2021-10-09T15:10:24Z",
		updated_at: "2022-12-17T15:08:20Z",
		pushed_at: "2022-12-14T03:57:56Z",
		git_url: "git://github.com/babakfp/svelte-outclick.git",
		ssh_url: "git@github.com:babakfp/svelte-outclick.git",
		clone_url: "https://github.com/babakfp/svelte-outclick.git",
		svn_url: "https://github.com/babakfp/svelte-outclick",
		homepage: "https://babakfp.ir/docs/svelte-outclick",
		size: 89,
		stargazers_count: 43,
		watchers_count: 43,
		language: "Svelte",
		has_issues: true,
		has_projects: false,
		has_downloads: true,
		has_wiki: false,
		has_pages: false,
		has_discussions: false,
		forks_count: 4,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: {
			key: "mit",
			name: "MIT License",
			spdx_id: "MIT",
			url: "https://api.github.com/licenses/mit",
			node_id: "MDc6TGljZW5zZTEz",
		},
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: [
			"click-outside",
			"on-click-outside",
			"outside-click",
			"svelte",
			"svelte-click-outside",
			"svelte-on-click-outside",
			"svelte-on-outclick",
			"svelte-on-outside-click",
			"svelte-outclick",
			"svelte-outside-click",
			"sveltejs",
		],
		visibility: "public",
		forks: 4,
		open_issues: 0,
		watchers: 43,
		default_branch: "main",
		temp_clone_token: null,
		network_count: 4,
		subscribers_count: 2,
		weeklyDownloads: 533,
	},
	{
		id: 533898811,
		node_id: "R_kgDOH9KmOw",
		name: "tailwindcss-addons",
		full_name: "babakfp/tailwindcss-addons",
		private: false,
		owner: {
			login: "babakfp",
			id: 44144724,
			node_id: "MDQ6VXNlcjQ0MTQ0NzI0",
			avatar_url: "https://avatars.githubusercontent.com/u/44144724?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/babakfp",
			html_url: "https://github.com/babakfp",
			followers_url: "https://api.github.com/users/babakfp/followers",
			following_url: "https://api.github.com/users/babakfp/following{/other_user}",
			gists_url: "https://api.github.com/users/babakfp/gists{/gist_id}",
			starred_url: "https://api.github.com/users/babakfp/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/babakfp/subscriptions",
			organizations_url: "https://api.github.com/users/babakfp/orgs",
			repos_url: "https://api.github.com/users/babakfp/repos",
			events_url: "https://api.github.com/users/babakfp/events{/privacy}",
			received_events_url: "https://api.github.com/users/babakfp/received_events",
			type: "User",
			site_admin: false,
		},
		html_url: "https://github.com/babakfp/tailwindcss-addons",
		description: "A Tailwindcss plugin that adds extra utilities and more.",
		fork: false,
		url: "https://api.github.com/repos/babakfp/tailwindcss-addons",
		forks_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/forks",
		keys_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/keys{/key_id}",
		collaborators_url:
			"https://api.github.com/repos/babakfp/tailwindcss-addons/collaborators{/collaborator}",
		teams_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/teams",
		hooks_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/hooks",
		issue_events_url:
			"https://api.github.com/repos/babakfp/tailwindcss-addons/issues/events{/number}",
		events_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/events",
		assignees_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/assignees{/user}",
		branches_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/branches{/branch}",
		tags_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/tags",
		blobs_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/git/blobs{/sha}",
		git_tags_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/git/tags{/sha}",
		git_refs_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/git/refs{/sha}",
		trees_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/git/trees{/sha}",
		statuses_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/statuses/{sha}",
		languages_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/languages",
		stargazers_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/stargazers",
		contributors_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/contributors",
		subscribers_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/subscribers",
		subscription_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/subscription",
		commits_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/commits{/sha}",
		git_commits_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/git/commits{/sha}",
		comments_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/comments{/number}",
		issue_comment_url:
			"https://api.github.com/repos/babakfp/tailwindcss-addons/issues/comments{/number}",
		contents_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/contents/{+path}",
		compare_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/compare/{base}...{head}",
		merges_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/merges",
		archive_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/{archive_format}{/ref}",
		downloads_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/downloads",
		issues_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/issues{/number}",
		pulls_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/pulls{/number}",
		milestones_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/milestones{/number}",
		notifications_url:
			"https://api.github.com/repos/babakfp/tailwindcss-addons/notifications{?since,all,participating}",
		labels_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/labels{/name}",
		releases_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/releases{/id}",
		deployments_url: "https://api.github.com/repos/babakfp/tailwindcss-addons/deployments",
		created_at: "2022-09-07T18:51:21Z",
		updated_at: "2022-12-14T02:15:00Z",
		pushed_at: "2022-12-14T03:55:39Z",
		git_url: "git://github.com/babakfp/tailwindcss-addons.git",
		ssh_url: "git@github.com:babakfp/tailwindcss-addons.git",
		clone_url: "https://github.com/babakfp/tailwindcss-addons.git",
		svn_url: "https://github.com/babakfp/tailwindcss-addons",
		homepage: "https://babakfp.ir/docs/tailwindcss-addons",
		size: 115,
		stargazers_count: 0,
		watchers_count: 0,
		language: "JavaScript",
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: {
			key: "mit",
			name: "MIT License",
			spdx_id: "MIT",
			url: "https://api.github.com/licenses/mit",
			node_id: "MDc6TGljZW5zZTEz",
		},
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: ["tailwindcss"],
		visibility: "public",
		forks: 0,
		open_issues: 0,
		watchers: 0,
		default_branch: "main",
		temp_clone_token: null,
		network_count: 0,
		subscribers_count: 1,
		weeklyDownloads: 500,
	},
]
